language: node_js
node_js:
- '6'
env:
- CXX=g++-4.8
services:
- mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install
- npm test
- npm run docs
deploy:
  provider: heroku
  api_key:
    secure: nTv2QhCG3vvuieVDP2sU5is5e2PcWkgkP+4ZNREnY/ANTkoY5ZA7pEeoeWt/EUBN5SsjQYl4RrkS8LiQQijTEz9SgiR1Ah6hN6Po0pY5t8BZYm5m7hYq3vK//NwRor6qzJzIL/wJQ7GYsl3vLB9manWcbvdPQMLnXuwquQABG0EDk+rsQWmIX2Av3xqm5E1R3bXGWZTEyXtlznFw92nyG7/oC51GWo1Ktl94lWnpDqJ9215fI3KLiGtV/HM8btQChhx+8zzb6nyrQDTffVaaA6s4QJZzMZF/JiFMcNnH9JNHuHRza8eWwT+rt/asSJ37fib+0fGYyF99XkRjtwlpX9EvH1ARaFKEq6TB+aAWkF2ZxT+eyVbuHMP//AlS/dzCaS2uVLOcFhGvQEv3avAAwP9DnxrsONtRjlm05XQTtlhBXwPf2q4s3Ab0PDRwzWWP5mSSWw/jXLWYJ/wwW1SF8QUpRZPtkxI7CBGQEO914ajnAECgXts1Lt7/fMszNHejo6wQJvTRsr7Sa7rCAgi3O/QKH/2luBR65fer1YjlU0xKBZpIEhh7aGhyRLP7ASqoC3rJQQul+RuCJktWv2i6nwTCg7N/aWzuYHK3Rl1FbRNSXdAdS3627pLk7GzUOzTjhaLSxjQQ/YJN+FvwRHx54HWmBnoArWTq2rLA18DSupE=
